Resources:
  handler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: app.universy.lambda.DummyHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          AWS_REGION: sa-east-1
          STAGE: dev
